"""empty message

Revision ID: c6e08cbd7a68
Revises: 
Create Date: 2019-08-06 15:44:13.603227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6e08cbd7a68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_index('completed', table_name='todos')
    op.drop_index('title', table_name='todos')
    op.drop_column('todos', 'userid')
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('todos', sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.create_index('title', 'todos', ['title'], unique=True)
    op.create_index('completed', 'todos', ['completed'], unique=True)
    op.drop_column('todos', 'userId')
    # ### end Alembic commands ###
